name: moyasar
description: Accept payments in your Flutter app with ease by using Moyasar. With this SDK, you can quickly and safely accept payments through Apple Pay, Samsung Pay, STC Pay and Credit Card (with managed 3DS step).
version: 3.0.1
homepage: https://moyasar.com/en/
repository: https://github.com/moyasar/moyasar-flutter
issue_tracker: https://github.com/moyasar/moyasar-flutter/issues

environment:
  sdk: ">=2.18.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  pay: ^3.2.1
  plugin_platform_interface: ^2.0.2
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.samsung.flutter.sdk.samsungpay.v2.samsung_pay_sdk_flutter
        pluginClass: SamsungPaySdkFlutterPlugin
      ios:
        pluginClass: SwiftPlugin
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Regular.ttf
        - asset: assets/fonts/Aeonik-Medium.ttf
          weight: 500
